# Generated by Django 5.2.5 on 2025-08-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(choices=[('NY.GDP.MKTP.CD', 'GDP (current US$)'), ('SP.POP.TOTL', 'Population, total'), ('NY.GDP.PCAP.CD', 'GDP per capita (current US$)'), ('FP.CPI.TOTL.ZG', 'Inflation, consumer prices (annual %)'), ('SL.UEM.TOTL.ZS', 'Unemployment, total (% of total labor force)'), ('NE.TRD.GNFS.ZS', 'Trade (% of GDP)')], db_index=True, max_length=20)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('value', models.FloatField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='dashboard_app.country')),
            ],
            options={
                'ordering': ['country', 'indicator_code', 'year'],
                'unique_together': {('country', 'indicator_code', 'year')},
            },
        ),
    ]
