# Generated by Django 5.2.5 on 2025-08-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(choices=[('NY.GDP.MKTP.CD', 'GDP (current US$)'), ('SP.POP.TOTL', 'Population, total'), ('NY.GDP.PCAP.CD', 'GDP per capita (current US$)'), ('FP.CPI.TOTL.ZG', 'Inflation, consumer prices (annual %)')], max_length=20)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.country')),
            ],
            options={
                'unique_together': {('country', 'indicator_code', 'year')},
            },
        ),
    ]
